version: "3"

services:
  app:
    build: .
    networks:
      - docker-dev-network
    container_name: simulator
    volumes:
      - .:/go/src/
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
networks:
  docker-dev-network:
    external: true
